### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "hailyduong@gmail.com",
  "password": "Pass@123"
}


### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "hailyduong@gmail.com",
  "password": "Pass@123"
}


### Logout user
POST http://localhost:3000/api/auth/logout


### Request Password Reset
POST http://localhost:3000/api/auth/password-reset/request
Content-Type: application/json

{
  "email": "user@example.com"
}


### Confirm Password Reset
POST http://localhost:3000/api/auth/password-reset/confirm
Content-Type: application/json

{
  "token": "your_reset_token_here",
  "newPassword": "newPassword123"
}
